### ISSUE TITLE
Secure connection to releases.multiviewer.app failed

### ISSUE THREAD

**Issue by chrisDwarner** [f1multiviewer/issue-tracker#341]
I have been trying to download your app and all the browsers I try fail to establish a secure connection 

https://releases.multiviewer.app/download/97834579/MultiViewer.for.F1-1.12.10-x64.dmg

chrome:
This site can’t provide a secure connectionreleases.multiviewer.app sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

FireFox
Secure Connection Failed

An error occurred during a connection to releases.multiviewer.app. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by imBigo** [comment]
I've fixed this by using me phone's data to download the file. I shared my connection to my PC. Hopefully you can download it on your phone and transfer the file?

**Comment by f1multiviewer** [comment]
This exact issue is due to your ISP blocking MultiViewer's domains:

You may be on Xfinity or another ISP that uses their security software, which has erroneously flagged a couple of our domains. You can go to Comcast Xfinity Mobile App -> Account Icon on Top Left -> Scroll down to More Resources -> xFi Advanced Security -> Turn Off, to make sure everything works like normal again.

**Comment by chrisDwarner** [comment]
sigh craptastic comcastic (xfinity) strikes again

ok to close this

**Comment by f1multiviewer** [comment]
I've added several enhancements, including `multiviewer.dev` as mirror. I've also added backups in case this happens again, so updates would still be able to go through if this re-occurs.
