### ISSUE TITLE
GP Radio (Netherlands)

### ISSUE THREAD

**Issue by Deojuvente** [f1multiviewer/issue-tracker#438]
When I use Multiviewer, I cannot access the menu option in GP Radio, which says 'Radio channel with Dutch commentary. Not available in the Netherlands due to licensing restrictions.' However, when I visit the website directly, I can listen live without using a VPN (https://grandprixradio.be/radio-luisteren). Why does Multiviewer indicate that there are licensing restrictions?

**Comment by JustJoostNL** [comment]
Hey @martijnvankekem,

> However, when I visit the website directly, I can listen live without using a VPN 

If you open the commentary stream on the website in the Netherlands (without VPN), it checks if you have access to the commentary stream, when not it will play the normal music stream. So I assume you heard the music instead of the commentary?

MultiViewer won’t play the music stream when you don’t have access to the commentary stream, which results in no audio playback.

Also, about the following:

> The fact that the official website doesn't country-restrict listeners

This isn’t true, GP Radio does allow access to the commentary stream to all countries except the Netherlands (they block the Netherlands specifically). Also all the blocking is on GP Radio’s end, and MultiViewer doesn’t block anything.

**Comment by JustJoostNL** [comment]
Hey,

> However, when I visit the website directly, I can listen live without using a VPN 

If you open the commentary stream on the website in the Netherlands (without VPN), it checks if you have access to the commentary stream, when not it will play the normal music stream. So I assume you heard the music instead of the commentary?

MultiViewer won’t play the music stream when you don’t have access to the commentary stream, which results in no audio playback.

Also, about the following:

> The fact that the official website doesn't country-restrict listeners

This isn’t true, GP Radio does allow access to the commentary stream to all countries except the Netherlands (they block the Netherlands specifically). Also all the blocking is on GP Radio’s end, and MultiViewer doesn’t block anything, it only displays the warning.

**Comment by f1multiviewer** [comment]
Going to close this as not planned.
